// pch.h
#pragma once
#include <windows.h>
#include <commctrl.h>
#include <shellapi.h>
#include <shlobj.h>
#include <shobjidl.h>
#include <string>
#include <functional>
#pragma comment(lib,"shell32.lib")
#pragma comment(lib,"comctl32.lib")