name: Build Windows EXE

on:
  push:
    tags: [ "v*" ]           # 每次打 tag v* 时触发
  workflow_dispatch:         # 也可手动触发

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Release x64
      run: |
        msbuild DesktopIconController2.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload exe to release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/Release/DesktopIconController.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
